### ISSUE TITLE
Python2nix builder fails for older dependencies without pyproject.toml

### ISSUE THREAD

**Issue by TakodaS** [nix-community/pyproject.nix#169]
```nix
#flake.nix
{
  description = "Pyproject building a uv project";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    pyproject-nix = {
      url = "github:nix-community/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    uv2nix = {
      url = "github:adisbladis/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs @ {
    nixpkgs,
    flake-parts,
    pyproject-nix,
    uv2nix,
    ...
  }:
    flake-parts.lib.mkFlake {inherit inputs;}
    {
      systems = nixpkgs.lib.systems.flakeExposed;

      perSystem = {
        config,
        pkgs,
        ...
      }: let
        inherit (nixpkgs) lib;

        workspace = uv2nix.lib.workspace.loadWorkspace {workspaceRoot = ./.;};

        # Create package overlay from workspace.
        overlay = workspace.mkPyprojectOverlay {
          sourcePreference = "wheel"; # or sourcePreference = "sdist";
        };

        python = pkgs.python3;
        pythonSet =
          (pkgs.callPackage pyproject-nix.build.packages {
            inherit python;
          })
          .overrideScope
          overlay;
        devPackages = with pkgs; [python uv];

      in {

        devShells.dev = pkgs.mkShell {
          packages = devPackages;
        };
        devShells.default = let

          # Override previous set with our overrideable overlay.

          # Build virtual environment
          virtualenv = pythonSet.mkVirtualEnv "dev-env" {
            pytest = [];
          };
        in
          pkgs.mkShell {
            packages = [virtualenv ];
            shellHook = ''
              # Undo dependency propagation by nixpkgs.
              unset PYTHONPATH
              # Get repository root using git. This is expanded at runtime by the editable `.pth` machinery.
              export REPO_ROOT=$(git rev-parse --show-toplevel)
            '';
          };

      };
    };
}
```
```toml
#pyproject.toml
[project]
name = "pytest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docopt>=0.6.2",
]

[build-system]
requires = [ "hatchling","setuptools"]
build-backend = "hatchling.build"
```

gives 
```bash
ModuleNotFoundError: No module named 'setuptools'
ERROR Backend 'setuptools.build_meta:__legacy__' is not available.
```

I also tried
```toml
[build-system]
requires = [ "setuptools"]
build-backend = "setuptools.build_meta"
```

But this fails the same way. I could use the hacks module, but I feel there is a better way using overriding one of the pyproject hooks to set something equivalent to `pyproject = false` in nixpkgs' `buildPythonPackage` if a pyproject toml is not found.
