### ISSUE TITLE
Compatibility with importlib for obtaining a version?

### ISSUE THREAD

**Issue by silky** [nix-community/pyproject.nix#66]
It's common to define a version with:

```python
__version__ = version("my-lib")
```

where you also have:

```toml
[project]
# ...
dynamic = ["version"]

[build-system]
requires = ["setuptools>=64", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
```

in your `pyproject.toml`.

it'd be very convenient if this worked.

the problem appears to be that `my-lib` isn't available as a package.

Is it possible to get this working somehow?

I recall having a very similar problem with poetry2nix; but I feel like there has to be some solution with an editable package and site-packages? but maybe not?
